Vetores
```{r}
# na criacao de um vetor com varios numeros usar o c( )
# vetor do tipo numerico
X  = c(1,2,3,4,5,6)  
X 
## em R os vetores se iniciam em 1
X[1]
X[1] = 10
X[1]
```
Vetores de outros tipos
```{r}
# vetor do tipo texto
Y = c("a","b","c","d")
Y
# vetor do tipo inteiro
Z = c(1L,2L,3L)
Z
# retornar o tipo de dado do vetor 
# (vai retonar o tipo referente ao conteudo Ex: integer)
class(Z)
```
Matrizes
```{r}
VADeaths
colnames(VADeaths)
rownames(VADeaths)
```
Matrizes
```{r}
#só coluna 1
VADeaths[,1] # não limita linhas, mas apenas coluna 1
#so linha 1
VADeaths[1,] # todas as colunas da linha 1
#linhas 1 até 3
VADeaths[1:3,] # linha 1 a 3 com todas as colunas 
# linhas 1, 3, 5 
VADeaths[c(1,3,5),]
```
Data Frame
```{r}
# Um dataframe suporta tipos diferentes dentro da tabela
longley
#funcina como matriz
longley[,1:3]
#acessar coluna com $
longley$Unemployed
#ou nome
longley['Unemployed']
```
Listas
```{r}
# uma LISTAS Permite varios conjuntos de dados de tipos diferentes 
# no exemplo temos uma 3 conjuntos, matrix, array e vetor numerico
ability.cov 
#acessando elementos
ability.cov$cov
ability.cov[1]
#verificando que são objetos diferentes
class( ability.cov$cov)
class( ability.cov$center)
#acesando elemento dentro da lista
ability.cov$cov[,1:3]
```
Fatores
```{r}
#fatores
state.region
```

