---
title: "Capítulo 02"
subtitle: "Aula 01 - Comandos Básicos"
author: "Christian Bits"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Comandos Básicos

```{R}
print("Olá mundo!")
```

```{R}
2+2
```

```{R}
# imprimir de 0 a 100
0:100
```

# Armazenando valores em variáveis

## Valores individuais

```{r}
# atribuicao
a <- 1
```

```{r}
# também é possivel atribuir da esquerda pra direita, mas não é uma boa pratica
2 -> b
```

```{r}
# atribuicao multipla
c <- d <- e <- 3
```

## Múltiplos valores

```{r}
# atribuindo um vetor a funcao 
x <- c(1, 2, 5, 9)
x
```

# Sequências

```{r}
0:10
```

```{r} 
10:0
```

```{r}
seq(10)  # conta de 1 a 10 Crescente de 1 a 10
seq(30, 0, by = -3)  # conta de 30 ate 0 Decrescendo de 3 em 3
# OBS: em R a contagem se inicia do 1 ao contrario de outras linguagens que começamm de 0
```

# Matemática básica

```{r}
(y <- c(5, 1, 0, 10))
```

```{r}
x + y
```

```{r}
x * 2
```

```{r}
2^6
```

```{r}
sqrt(64)
```

```{r}
log(100)
```

```{r}
log10(100)
```

# Limpeza

Limpando o ambiente
```{r}
rm(list = ls()) 
```

Limpando o console
```{r}
cat("\014")
```

Limpeza terminada 
